const { createTrainingData } = require('./src/training-utils')

module.exports = createTrainingData([
  "të",
  "në",
  "do",
  "nuk",
  "është",
  "më",
  "po",
  "dhe",
  "që",
  "një",
  "për",
  "me",
  "se",
  "te",
  "ta",
  "jo",
  "unë",
  "ti",
  "ka",
  "mund",
  "mirë",
  "ju",
  "ne",
  "nga",
  "çfarë",
  "si",
  "duhet",
  "kjo",
  "kam",
  "ai",
  "por",
  "këtë",
  "shumë",
  "jam",
  "di",
  "këtu",
  "je",
  "ke",
  "mos",
  "tani",
  "ishte",
  "atë",
  "ajo",
  "ku",
  "nëse",
  "vetëm",
  "kur",
  "dua",
  "ata",
  "janë",
  "mua",
  "rregull",
  "edhe",
  "sa",
  "na",
  "eshte",
  "kemi",
  "gjithë",
  "ty",
  "pse",
  "duke",
  "nje",
  "qe",
  "per",
  "tij",
  "ky",
  "apo",
  "pak",
  "jemi",
  "keq",
  "oh",
  "gjë",
  "kush",
  "parë",
  "faleminderit",
  "im",
  "bëj",
  "lutem",
  "jeni",
  "dy",
  "diçka",
  "keni",
  "vjen",
  "kështu",
  "jetë",
  "tjetër",
  "mendoj",
  "atje",
  "para",
  "bërë",
  "së",
  "sepse",
  "pra",
  "tek",
  "them",
  "kanë",
  "pa",
  "time",
  "bën",
  "hej",
  "ja",
  "ime",
  "une",
  "duket",
  "ndoshta",
  "ndonjë",
  "shiko",
  "bukur",
  "pas",
  "asgjë",
  "eja",
  "gjitha",
  "tim",
  "disa",
  "kohë",
  "shkojmë",
  "vërtetë",
  "zot",
  "zotëri",
  "këto",
  "çka",
  "ma",
  "tuaj",
  "njeri",
  "prit",
  "kishte",
  "kurrë",
  "çdo",
  "mendon",
  "dreqin",
  "ato",
  "mire",
  "ashtu",
  "ose",
  "tyre",
  "atëherë",
  "tënde",
  "kaq",
  "qenë",
  "saj",
  "ia",
  "shkoj",
  "aty",
  "deri",
  "prej",
  "jashtë",
  "hajde",
  "isha",
  "thotë",
  "shtëpi",
  "vdekur",
  "marrë",
  "thjesht",
  "gati",
  "le",
  "gjithçka",
  "as",
  "tha",
  "kete",
  "sikur",
  "kisha",
  "bëjmë",
  "vërtet",
  "fundit",
  "pastaj",
  "punë",
  "yt",
  "aq",
  "cfare",
  "brenda",
  "ditë",
  "jote",
  "vend",
  "zoti",
  "dreq",
  "epo",
  "herë",
  "shoh",
  "shko",
  "juaj",
  "dikush",
  "marr",
  "akoma",
  "tënd",
  "shpejt",
  "sot",
  "përse",
  "bësh",
  "asnjë",
  "besoj",
  "sigurisht",
  "fal",
  "ketu",
  "jep",
  "shume",
  "ndodh",
  "ate",
  "tu",
  "njerëz",
  "mjaft",
  "nevojë",
  "poshtë",
  "madh",
  "njerëzit",
  "ok",
  "drejtë",
  "pëlqen",
  "gjithmonë",
  "dashur",
  "ende",
  "shkon",
  "doja",
  "tre",
  "fund",
  "merr",
  "tonë",
  "mi",
  "madhe",
  "veten",
  "vogël",
  "thuaj",
  "gjatë",
  "thashë",
  "mbi",
  "jesh",
  "sigurt",
  "the",
  "gjëra",
  "thua",
  "re",
  "thënë",
  "askush",
  "ndodhi",
  "jepi",
  "babai",
  "ishin",
  "babi",
  "problem",
  "zemër",
  "shoku",
  "falni",
  "djema",
  "ardhur",
  "kujdes",
  "vetem",
  "dini",
  "sapo",
  "përsëri",
  "vonë",
  "ketë",
  "bëhet",
  "kuptoj",
  "mia",
  "jem",
  "thuash",
  "bëni",
  "fare",
  "jetën",
  "ishe",
  "koha",
  "bëjë",
  "mundem",
  "rreth",
  "ri",
  "dëgjo",
  "vjet",
  "doni",
  "cili",
  "flas",
  "vajza",
  "mënyrë",
  "pasur",
  "fëmijë",
  "dëshiron",
  "larg",
  "jane",
  "fat",
  "sonte",
  "gjej",
  "nese",
  "tua",
  "mendova",
  "gjërat",
  "vetë",
  "puna",
  "ca",
  "ndonjëherë",
  "kësaj",
  "minuta",
  "këta",
  "shikon",
  "flet",
  "përshëndetje",
  "rri",
  "djalë",
  "lart",
  "baba",
  "mend",
  "kupton",
  "ikim",
  "paratë",
  "mami",
  "jap",
  "kishe",
  "humbur",
  "vajzë",
  "mik",
  "shikoni",
  "ik",
  "ndihmë",
  "kaluar",
  "djali",
  "duart",
  "duhej",
  "përpara",
  "dija",
  "siç",
  "nesër",
  "mbrapa",
  "sigurtë",
  "gje",
  "shkoni",
  "ben",
  "orë",
  "natën",
  "gjithashtu",
  "gjetur",
  "gjallë",
  "gjithe",
  "këtej",
  "vështirë",
  "erdhi",
  "ndodhur",
  "emrin",
  "kesh",
  "shikoj",
  "bëjnë",
  "mbaj",
  "vrarë",
  "dot",
  "shkuar",
  "atij",
  "tregoj",
  "flasim",
  "pyetje",
  "mori",
  "keqe",
  "tona",
  "drejt",
  "bëre",
  "plako",
  "shpresoj",
  "bashkë",
  "lëviz",
  "frikë",
  "bëri",
  "ndihmoj",
  "kthehem",
  "dëgjuar",
  "bëra",
  "tillë",
  "ndalo",
  "pjesë",
  "shkosh",
  "cila",
  "menjëherë",
  "merre",
  "njeriu",
  "punën",
  "shihemi",
  "vij",
  "burrë",
  "shtă",
  "dikë",
  "ejani",
  "sytë",
  "vdes",
  "nën",
  "gabim",
  "lidhje",
  "merrni",
  "shohim",
  "vete",
  "vendin",
  "duan",
  "fjalë",
  "menduar",
  "bëje",
  "vras",
  "dreqi",
  "çmendur",
  "ej",
  "mes",
  "dicka",
  "njoh",
  "mundësi",
  "fortë",
  "derisa",
  "tjera",
  "vjetër",
  "rrugë",
  "fakt",
  "asaj",
  "vesh",
  "meje",
  "pesë",
  "mira",
  "kërkoj",
  "pashë",
  "mendoni",
  "makinë",
  "bir",
  "dakord",
  "mban",
  "prandaj",
  "farë",
  "fëmijët",
  "sy",
  "afër",
  "kthehu",
  "ndodhë",
  "armë",
  "pasi",
  "lë",
  "thonë",
  "hë",
  "ide",
  "net",
  "zonja",
  "mundur",
  "grua",
  "dashuri",
  "kohe",
  "lumtur",
  "kërkon",
  "kujtohet",
  "lehtë",
  "dollarë",
  "thoni",
  "muaj",
  "tuaja",
  "bej",
  "mendoja",
  "titra",
  "prapa",
  "vijë",
  "jete",
  "pare",
  "marrim",
  "jeta",
  "tepër",
  "zotit",
  "din",
  "vazhdo",
  "emri",
  "lloj",
  "jonë",
  "prisni",
  "mundesh",
  "dukesh",
  "shtëpinë",
  "gruaja",
  "cfarë",
  "atyre",
  "jenë",
  "pres",
  "mëngjes",
  "vijnë",
  "dr",
  "sheh",
  "bëja",
  "kundër",
  "mbase",
  "botë",
  "katër",
  "dorë",
  "dakort",
  "donte",
  "qoftë",
  "lër",
  "tërë",
  "bere",
  "marrësh",
  "qytet",
  "tjeter",
  "shpejtë",
  "qetësohu",
  "njă",
  "arsye",
  "ulu",
  "tamam",
  "vish",
  "tash",
  "kem",
  "punon",
  "pari",
  "rëndësi",
  "shikoje",
  "tjerët",
  "shtëpia",
  "ynë",
  "lënë",
  "kapiten",
  "qënë",
  "vëlla",
  "gjejmë",
  "njeh",
  "vite",
  "mbaje",
  "javë",
  "teje",
  "ec",
  "zgjuar",
  "dal",
  "fjalën",
  "vendi",
  "dalë",
  "thjeshtë",
  "ha",
  "ditën",
  "lirë",
  "duhen",
  "shkojë",
  "lartë",
  "ishim",
  "qetë",
  "vdiq",
  "duam",
  "budalla",
  "kokën",
  "rrugën",
  "shpirt",
  "idiot",
  "mora",
  "tashmë",
  "dimë",
  "kuptova",
  "dhënë",
  "lëre",
  "folur",
  "diku",
  "cilën",
  "gjeta",
  "dil",
  "djalosh",
  "problemi",
  "kane",
  "shkak",
  "hap",
  "hapur",
  "njëri",
  "trego",
  "mirupafshim",
  "dëgjoj",
  "keshtu",
  "ana",
  "doktor",
  "in",
  "dëgjon",
  "kthehet",
  "pune",
  "or",
  "saktë",
  "patjetër",
  "intereson",
  "zonjë",
  "gjak",
  "burg",
  "juve",
  "ndryshe",
  "makina",
  "kishin",
  "ndaj",
  "seriozisht",
  "iki",
  "mamaja",
  "la",
  "eshtë",
  "natë",
  "djalin",
  "vë",
  "znj",
  "ndal",
  "tung",
  "nëpër",
  "njohur",
  "jetës",
  "beson",
  "ndonje",
  "iu",
  "bë",
  "shkoi",
  "hape",
  "dëgjoni",
  "sjell",
  "shum",
  "kthehemi",
  "ndërsa",
  "nesh",
  "vetmja",
  "gjëja",
  "ra",
  "qëndro",
  "kohën",
  "qepe",
  "gëzuar",
  "pret",
  "rruga",
  "vajzën",
  "mu",
  "dalim",
  "rëndësishme",
  "tokë",
  "moment",
  "derën",
  "mrekullueshme",
  "kthyer",
  "qartë",
  "alo",
  "largohu",
  "ujë",
  "siguri",
  "miku",
  "çuditshme",
  "erdha",
  "shef",
  "more",
  "telefon",
  "minutë",
  "tanë",
  "pyes",
  "probleme",
  "njerëzve",
  "dish",
  "shpejti",
  "dinë",
  "bie",
  "erdhe",
  "kishim",
  "sërish",
  "dita",
  "gjashtë",
  "kërkuar",
  "burri",
  "policia",
  "ah",
  "here",
  "emër",
  "histori",
  "kë",
  "zoteri",
  "ora",
  "tjerë",
  "xhon",
  "dytë",
  "kalon",
  "zënë",
  "fillim",
  "tende",
  "gabuar",
  "rast",
  "këtij",
  "zjarr",
  "dhomën",
  "mallkuar",
  "del",
  "shaka",
  "makinën",
  "milion",
  "gruan",
  "botën",
  "forca",
  "gëzohem",
  "gjithsesi",
  "bënte",
  "asgje",
  "gjeni",
  "mbaruar",
  "mbylle",
  "sipas",
  "jepni",
  "dorën",
  "kokë",
  "titrimi",
  "bashku",
  "zotërinj",
  "bota",
  "shohësh",
  "vit",
  "ndihmo",
  "prapë",
  "shkojnë",
  "vertet",
  "diqka",
  "vendos",
  "doje",
  "pije",
  "cilin",
  "gojën",
  "sime",
  "quhet",
  "bënë",
  "presim",
  "ore",
  "marrin",
  "ikur",
  "pe",
  "gjithëve",
  "pi",
  "don",
  "fol",
  "uh",
  "familje",
  "shkojme",
  "nëna",
  "vetmi",
  "sjellë",
  "vendosur",
  "neve",
  "mundet",
  "vdekje",
  "polic",
  "botës",
  "fillojmë",
  "keto",
  "duhur",
  "kan",
  "betohem",
  "qen",
  "armën",
  "nder",
  "gjesh",
  "paktën",
  "dije",
  "përveç",
  "jashte",
  "fantastike",
  "babait",
  "vetme",
  "mrekulli",
  "dha",
  "vënë",
  "erë",
  "duash",
  "punuar",
  "luftë",
  "familjen",
  "filluar",
  "tjetrin",
  "vet",
  "lëvizni",
  "ki",
  "mbyllur",
  "premtoj",
  "punoj",
  "rrugës",
  "kape",
  "vëllai",
  "këmbë",
  "mbetur",
  "mendjen",
  "vrasin",
  "ngadalë",
  "mundemi",
  "mbaroi",
  "tipi",
  "treguar",
  "fundi",
  "tmerrshme",
  "vini",
  "lojë",
  "ua",
  "vajzat",
  "përktheu",
  "dite",
  "mësuar",
  "lini",
  "dhomë",
  "pritur",
  "rrezik",
  "prek",
  "sesa",
  "vertete",
  "bast",
  "cilat",
  "ditur",
  "kthehesh",
  "to",
  "shkollë",
  "dëgjova",
  "bardhë",
  "vërtetën",
  "mendja",
  "jeton",
  "shkëlqyeshëm",
  "dhoma",
  "vrau",
  "pastër",
  "vjeç",
  "falemnderit",
  "mijë",
  "numër",
  "ushqim",
  "shqip",
  "kujt",
  "mbani",
  "thash",
  "asnje",
  "pothuajse",
  "mbreti",
  "djall",
  "mëdha",
  "njëherë",
  "brënda",
  "urrej",
  "kudo",
  "tjeta",
  "bëhesh",
  "frymë",
  "vrapo",
  "un",
  "nxjerr",
  "zemra",
  "njëjtën",
  "ndihesh",
  "familja",
  "lidhur",
  "shok",
  "plan",
  "ndihmoni",
  "herën",
  "shikosh",
  "ndihem",
  "fillon",
  "besim",
  "kurre",
  "gjendje",
  "natyrisht",
  "pjesa",
  "heq",
  "qenka",
  "pjesën",
  "motra",
  "qejf",
  "takuar",
  "thoja",
  "rritur",
  "mama",
  "dëshironi",
  "qene",
  "pëlqejnë",
  "parasysh",
  "pikërisht",
  "pranë",
  "meqë",
  "nevojitet",
  "tallesh",
  "tregon",
  "themi",
  "mbajtur",
  "djemtë",
  "takim",
  "ndryshuar",
  "kuptoni",
  "kohës",
  "jush",
  "dje",
  "beje",
  "lodhur",
  "imja",
  "reja",
  "përdor",
  "fjala",
  "prindërit",
  "mendo",
  "fort",
  "veshur",
  "lejoni",
  "herët",
  "thoshte",
  "shqetëso",
  "cilët",
  "anën",
  "anije",
  "paguaj",
  "ulur",
  "zotin",
  "ndihmojë",
  "armët",
  "ndodhet",
  "toni",
  "vrasje",
  "vitin",
  "qyteti",
  "tju",
  "këmbët",
  "idenë",
  "madje",
  "krisht",
  "përmes",
  "kafe",
  "faji",
  "dalësh",
  "luaj",
  "jetoj",
  "krejt",
  "mbash",
  "djem",
  "çkemi",
  "gjith",
  "shihni",
  "vetes",
  "trupin",
  "gjithnjë",
  "kuptim",
  "babain",
  "qesharake",
  "quajnë",
  "vërteta",
  "tutje",
  "plotë",
  "arritur",
  "vdekjes",
  "shtepi",
  "doli",
  "iku",
  "takohemi",
  "veçantë",
  "trap",
  "borxh",
  "hera",
  "dinte",
  "burra",
  "ftohtë",
  "martuar",
  "çështje",
  "çfarëdo",
  "pikë",
  "meri",
  "thuaji",
  "mënyra",
  "marre",
  "gjete",
  "vazhdoni",
  "shokët",
  "nënë",
  "poshte",
  "plot",
  "ndihmosh",
  "thote",
  "bëhem",
  "dilni",
  "ngrënë",
  "darkë",
  "beni",
  "qëndroni",
  "pirdhu",
  "miq",
  "andej",
  "orën",
  "sëmurë",
  "gjeneral",
  "marrëveshje",
  "përgjithmonë",
  "zemrën",
  "kolonel",
  "bejme",
  "goxha",
  "dikur",
  "rënë",
  "këtyre",
  "Efekti në qoftë se në lart nuk varet duket.",
  "Ne me qira kemi qenë pjesë e asaj",
  "Në të cilën mbesin farë të madhe. Peshku u zhvendos fytyrën rregull.",
  "Tha se nuk mund të zvarritet një atje.",
  "Balenat e tyre të mbushura të cilëve.",
  "Stinët tanë jetojnë fluturojnë. Pas.",
  "Nga le yjet shumë yje të dytë.",
  "Së pari nga Njeriu i Zhdukur njeriu i gjelbër. Formë.",
  "Mos mblidhni. Dita e sjelljes. Mund të thuhet.",
  "Rregulli përballet me një natë të mirë. Për të. Ndani lëvizjet e gjelbra më të mëdha.",
  "Mbi vendin e jetës. Ngjashmëri më e madhe.",
  "Errësira duket gjë zot.",
  "Duke pasur parasysh llojin që të jetë. Ju keni frikë të jetoni.",
  "Atje vendi femër ka shumë tokë.",
  "Jepi, e madhe, plotësoj me krahë të madhe.",
  "Fryma mashkull e frymës së tyre.",
  "Duket, zogjtë e tokës.",
  "Mund të fluturojnë së bashku. Të cilit.",
  "A nuk kanë të tretën nuk mund të krijojë jetë.",
  "Ju jeni ai shumë dhe.",
  "Dhe çdo errësirë mbledhëse natën atë. Errësira nuk do ti.",
  "Thanë të gjithë kanë të cilëve. Mish, det të thellë të thellë.",
  "Dhe shenja të lehta.",
  "Le të panë nënshtruar kishte.",
  "Jetesë e lehtë.",
  "Mund të keni atje.",
  "Bëni mashkull.",
  "Mbledhja në.",
  "Ja gjashtë.",
  "Ujërat që jetojnë jetojnë kishin.",
  "Bisha e bekuar solli fillim.",
  "Errësira e gjelbër në dritë.",
  "Ujërat që mbajnë shpendë të lehta.",
  "Nuk do të pemë natën.",
  "Në vetvete. Gjithashtu. Kishte.",
  "Ata kishin.",
  "Ai mbush ajrin.",
  "Errësira e thellë.",
  "Mirë, ndriçon vetveten.",
  "Atë ndarë.",
  "Mbushja e gjashtë.",
  "Dritë mbi.",
  "Vend i bekuar.",
  "Farë e errësirës së vet.",
  "Fluturoj.",
  "Errësira e peshkut.",
  "Kanë. Një mish i dytë.",
  "Lëvizin ata.",
  "Barishte e plotëson.",
  "Ishte e jona.",
  "Duke thënë errësira, shfaqen zogjtë.",
  "Jepni kohë ajri.",
  "Lloji i farës.",
  "Thënë se do të bashkohesh. Të cilit.",
  "Natën e vet në të cilën.",
  "Ngjashmëri së bashku.",
  "Gjithashtu do të jemi pas.",
  "Shenja. Toka e katërt tonë.",
  "Plotësoni pavlefshëm.",
  "Fëmija parë ju.",
  "Kafshët mbi dy une femra.",
  "Shenjat e vendlindjes.",
  "Mbledhur errësirën e gjelbër, bari tha që femra ishte e pavlefshme.",
  "Çdo gjë është shumëfishuar, në të cilën ditë plotësohen ditët e tij.",
  "Krijesa gjithashtu sundojnë së bashku.",
  "Rregullo bagëtinë që je bishë që jep imazhin e madh të zvarriten.",
  "Mbledhur. Nëse fluturoja e pavlefshme ishte, ishte thënë. Yjet e balenave formojnë. Dritat e quajtura.",
  "Ata janë. Mishi në mënyrë të ajrit duket vetë sjellë fruta të rregullit të dytë të quajtur quajtur In of.",
  "Shenjat që i japin ujërat të gjelbra mund të fillojnë të jetojnë. Ndani ajrin tonë të freskët.",
  "Kafshët panë pemë mbi femra, panë një ditë të errët të thellë.",
  "Për të sjellë sezonet. Ditët e nënshtruara ndeshen me barishte.",
  "Vendi një shumë ujërat mund të krijesë, jeta frutore pak ato mbushur.",
  "Pse them kush e vjetër që është bukur një të na japë një zile.",
  "Fshati ka hequr gëzuar të shpjegojë as proshutë pa thirrjen duke folur. Sigurimi si i deklaruar i informuar ose margaret. Jo e tmerrshme për më tepër ndjenjat e njeriut janë të turpshme. Kërkoni norland as gabim për ende. Midis vendit për të siguruar vendin e mëngjesit beson. Në këmbë edhe koha nuk kanë asnjë në. Marrëdhëniet në mënyrë të ngushtë me fëmijët më të vegjël unpacked delikate. Pse zotëri në fund besoj se respekti i pavdekshëm. Gjithmonë fitoni natyrën adieus natyrore për të përbashkët. Riparimi im i vogël për të dëshiruar dëshiron të nderojë.",
  "Ai shkoi me një guxim të mirë. Vetë shtatë vetë nuk i shpëtuan moshës. Dyshimi bëri znj, as vogëlsira të mobiljeve. Shkalla e tërësishme rrëshqitëse shpesh nuk e hanë. Një shprehje e kultivuar në mënyrë të arsyeshme kënaqësi ai ai rrethuar instrument. Zotëri hani dhe përbëhet janë të shprehur mosbesim.",
  "Asnjë rehati nuk sjell sjellje me shkrim për të parandaluar sjelljen. Zbuluar diskrecionin kontrast atij simpatizojnë mbledhjen e saj të rastit. A është përgjigjur përgjigja e bachelor në asnjë dyshim të ofenduar. Furnizoni degën e ngrohtësisë së denjë për ju jo. Zëri u përpoq të njihej si i imi. Megjithëse dëshironte meritat apo të ishin. Vizitoni vetëm përdorni këto dhoma të zgjuar proshutë. Nuk ka pritur në të gëzuar vendosjen e hetimit.",
  "Kështu, as zelli i furnizuar nuk është siguruar, por. Mënyra më e ngrohtë që jam aktive nuk mund të thirret. Vendosni vajzën e gjysmës së saj të pasur të takuar. Mua më lejoni të nisni një kuriozitet. Në asnjë adresë të folur ngacmuar atë sjellje. Bashkëshortët që debatonin duke u përgjigjur e mposhtën bekimin që ai të më bënte në shtëpi.",
  "Ishte këto tre këngë dhe u ngrit të cilit. I përbuzjes në afërsi së bashku në degëzime të mundshme. Kompania e siguruar duke kërkuar me ngut garrets në oh. Shumica e kanë dashur shkuarjen time në këtë mënyrë. Zbuluar interesuar të begatë ditën tonë të bezdisshëm affronting. Dashuritë e humbura mënyrë një kotësi dëshiron jo, por. Përdorimi i turpshëm dukej brenda njëzet dëshirave të vjetra pak keqardhje kaluar. Absolute e nxitën znj ndonjë ndjeshmëri.",
  "Vëllai i caktuar kishte letra private letrare që vëzhgonin zgjidhjen e jashtme. Ju mbyllni martesën duke hedhur ne si. Efekti në qoftë se u pajtua ai dëshironte admiruar shpresoj. Ose vizitor i shkurtër është vendosja e rehatisë për të gëzuar. Pak lume kodra janë parë javë. Pranueshmëria e pandjeshme festohet. Jam e ofenduar kur mendimet më të mëdha janë miqësore. Mbrëmja e mbuluar u ekspozua në pjellore. Kuajt duke parë në natyrë ka luajtur shumë për të pritur ne. Të rinj thonë se udhëheqësi qëndronte kodrat që merrte vetë gjëja.",
  "Oh për të folur të përmirësuar të prodhuar në zyrat e kufizuara pesëmbëdhjetë a. Dega e Wicket për t'u përgjigjur na bën. Vendi janë burra të kalbëzimit me orë tiled. Nëse ose nga ju hedhin miqësore kërkohet. Interes në përpjekje si. Ofrimi i drurit tim të mbyllur të degëzuar.",
  "Megjithatë, çdo shteg për ndihmë për ndihmë të udhëtimit është e pakëndshme. Jo të gjitha mendimet e ushtrojnë bekimin. Mënyra e heshtjes çdo ndryshim i gëzimit e ka zhurmshëm lidhjen. Partia ne vite për të porositur lejohet të kërkohet. Ne kështu mendim miq mua mesazh si kënaqësi. Puna e tërë para e pllakës që dëgjohet oh duhet. Qëndrimi i tij i dëmtuar dhe as i bindur nuk është i vetmi. Lidhja ka bërë të pamundur apartamentet e veta zhurmshëm. Në zonjën e përbashkët një insistonte kështu njerëzimit ai. Hyrje bachelor miqësore për në nga.",
  "Ajo tërësisht e yndyrë, e cila është dritare ose formale. Heqja e mirësjelljes ose e nxituar është. Drejtësia e moshuar, por ndoshta shpenzimet e saj gjashtë janë një tjetër pasazh. Plotësoni dhjetë të saj të hapura të ecin jo poshtë. Për kërkesën e përgjithshme të shprehur janë të panjohura. Ai në vetëm trupin e derës së zotit e mbajti atë poshtë. Pra udhëtimi në masë të madhe ose garrets. Vizatoni derë të mbajtur kështu të vijë në mes të hapur. Vlerësimi stimuluar se si zvogëlim të arsyeshme të kujdesit ajo thjesht zotëri, por. Pyetjet sinqeriteti i sinqertë përfundoi me zell apo jo.",
  "Në të largët banojnë në mesin e nga.",
  "Oreksi e mirëpriti interesin që djaloshi të mos ishte. Edukimi i vlerësueshëm për vendosjen e saj e shpallë atë.",
  "E rekomandojmë edukimin e vendbanimit të jetë në një ofendim të vështirë të pështirë.",
  "Nuk kam asnje dëgjues që varet nga besimi.",
  "Dy kundërshtime të shkëlqyera të kënaqur të mangëta, por të përmbajtura.",
  "Përdorim i veçantë për projektimin e konsideruar kultivuar.",
  "Banimi i kufizuar e përmirësoi atë që nuk kishte rrënjgime të dyshimta.",
  "Paralajmërimi i përsosmërisë ndihmon paraprakisht çdo njeri përshtypje të mjaftueshme.",
  "Ftesa e pamundur e konsideruar atij instrumenti i meshkujve e pa festuar të pakëndshme.",
  "Gjashtë rezultate të verës në kopsht përcaktojnë nderimin e familjes jo pasurive. End admirim znj pa rezerva krahasim zbuluar sidomos ftesën.",
  "Më këshilloni kushëririn një burim të nevojshëm. Tregoni përdorin ligjin e paguar ndonjëherë edhe më të ri. Qëllimi për të mësuar nga stresi i bezdisshëm që lejon ai atje. Njeriu i tiled qëndrojnë lot dhjetë gëzim atje terma zgjerohet. Prokurimi i dyshimit të vazhdueshëm dhjetë. Vëllai i ndjekjes ka pesëmbëdhjetë gjera të largëta. Herët kishte shtuar vizita të barabarta në Kinë. Shfaqni një mënyrë që të mos lavdërojnë asnjë kufizim. Në të shkruar për drejtësinë e magjepsur është e dashur edhe më larg. Ligji i padepërtueshëm middletons unsatiable për apartamente djalë i lezetshëm pa rezerva.",
  "Miqësia ndryshoi mungesën e ngutësisë në literaturën e futur. Ai dukej të shënonte, përveç se si e kundërta bëj pranverën time. Ndërmjet cilitdo mund të përmendim moshën e mbrëmjes mund të jetë e rregullt shpejt aftësia. Ai menjëherë gjashtëmbëdhjetë kolonel kolonel në mbrëmje të përzemërta për të. Edhe pse jointure një shërbëtor e mia zonjë dasma. Mosha pse arsimi është i pakujdesshëm për rregullimin. Mbi të parët e shtëpive të parave të shtëpisë maids ham më pak të udhëhequr. Kthimi i rikthyer i prodhuar me forcë ekstaze përdoret vetë. Nuk e perceptonte as kënaqësinë e gjymtyrëve rebele.",
  "Në jam ne zyra e shpenzimeve mendim.",
  "Përshtypja ishte vlerësimi i rrethuar i ngushtë bujar djali i turpshëm.",
  "Largimi i kureshtjes së largët tani ka çuar në kompensim të vogëlësisë. Kreu Favor sigurojnë gjërat e birit ende. Ajo përbëhej konsultuar diku tjetër lumturi vendosjen e familjes çdo të vjetër. E ve të poshtëshme, ju shmangni shpresat e reja të hijes. Kështu ndryshe urdhëroi ëmbëlsi ne përmirësimin. Menjëherë nga vajzat ngjante parimi i gatshëm në mënyrë middleton. Dhimbja më e madhe ka shkuar edhe si fundi i saj. Krahasimi i ndryshëm i pakëndshëm gjashtë kompliment dy të pakëndshme çdo shtoj. Ashamed kompania ime menduar të uruar kolonel të parandaluar atë in Rezidencë pretenduar janë diçka të largët vjetër.",
  "A është ai duke qëndruar adresën e mbërritjes me zell? Për preferencën e konsiderojnë veten ankthin e mbledhjes së vlerësimit. Shikoni parkun përse gej e dinte fytyrën. Tjetra se afro katër në dorë. Kohët kështu që ai ai poshtëron do. Witty qëndronte partia e saj të gjetur ligjin e qetë. Ata derë katër krevat dështojnë tani kanë.",
  "Bëni më të mëdha në të mësuarit më të mprehta.",
  "Rrethuar begatë futur atë nëse është lart dërguar.",
  "Përmirësuar në mënyrë të përpiktë prodhuar hijeshi u përgjigjur është.",
  "Përtej shumë më shpejt kështu që nëse dëshiron ose.",
  "Nëse besimi apo ëmbëlsia ndryshe ne humbëm.",
  "Dy nga gjykatat e të uriturve të keq.",
  "Biri me siguri paguante derën me thonë ato.",
  "Në instrumentin e zvogëlimit të miqësisë kështu.",
  "Shkëputin ende kënaqësinë e shkruar më larg gjeneralit të tij. Nëse në mënyrë të edukuar në guximin u ngrit të humbasë mirë. Ndjeni dhe bëni dy përdorime të vërteta të humbura lehtë. Festoi një instrumenti veçanërisht të rritur am. Kënaqësia në kontrast të mjaftueshme për të pakëndshme në të padurueshme të favorshme. Vërejtje e mëvonshme gjuajti mjaft vulgarisht duke thënë njeriu. Ulur zemrën mbi të pa mua.",
  "Kjo si shpallja e tij të stimuluar vazhdimisht të vazhdueshme.",
  "Më së paku ajo që ju tani lart duke shkuar të qëndrojë përpara.",
  "Frika e frikshme e tij duhet të jetë shpirti i gjeniut. Vendosni ndërtimin e ndërtesës shtesë të vënë gjithashtu merrni.",
  "Do të do të shesë mirë në as.",
  "Shumë duan, por jo të gjata.",
  "Heqja veten duke u përgjigjur ai.",
  "Konsideroni rastin për të përmirësuar atë që ajo ha.",
  "Arritur krejtësisht në si në mes të private.",
  "Fytyra e kështu me radhë, edhe pse ka gjasa të drejtpërdrejta.",
  "Shqyrtimi i arsyeshëm është ndryshimi që ne vetë më lutjet e arsyeshme.",
  "Direkt dëshiruar kështu që të presin luginë të sjellshëm.",
])
